Repository kan-bayashi/ParallelWaveGAN, pull requests merged in 2020-03, with the labels that each got.

#94 Fix typo
  egs/vctk/voc1/run.sh
Labels: bug

#95 New parallel job
  egs/arctic/voc1/run.sh
  egs/csmsc/voc1/run.sh
  egs/jnas/voc1/run.sh
  egs/jsut/voc1/run.sh
  egs/ljspeech/voc1/run.sh
  egs/vctk/voc1/run.sh
  egs/yesno/voc1/run.sh
  parallel_wavegan/__init__.py
  parallel_wavegan/bin/normalize.py
  parallel_wavegan/bin/preprocess.py
  setup.py
  utils/make_subset_data.sh
  utils/split_scp.pl
Labels: enhancement

#96 Support kaldi-style scp file in bin scripts
  parallel_wavegan/__init__.py
  parallel_wavegan/bin/compute_statistics.py
  parallel_wavegan/bin/decode.py
  parallel_wavegan/bin/normalize.py
  parallel_wavegan/bin/preprocess.py
  parallel_wavegan/bin/train.py
  parallel_wavegan/datasets/__init__.py
  parallel_wavegan/datasets/audio_mel_dataset.py
  parallel_wavegan/datasets/scp_dataset.py
  setup.py
Labels: enhancement

#97 Update VCTK recipe
  egs/vctk/voc1/conf/parallel_wavegan.v1.long.yaml
  egs/vctk/voc1/conf/parallel_wavegan.v1.yaml
  egs/vctk/voc1/local/data_download.sh
  egs/vctk/voc1/local/data_prep.sh
  egs/vctk/voc1/run.sh
Labels: enhancement

#98 Add new options
  parallel_wavegan/bin/decode.py
  parallel_wavegan/bin/normalize.py
  parallel_wavegan/bin/preprocess.py
  parallel_wavegan/bin/train.py
  utils/make_subset_data.sh
Labels: enhancement

#99 Support `sampling_rate_for_feats` option in config
  .github/workflows/ci.yaml
  egs/yesno/voc1/conf/parallel_wavegan.v1.debug.diff_fs.yaml
  parallel_wavegan/__init__.py
  parallel_wavegan/bin/preprocess.py
  setup.py
Labels: enhancement

#102 Add VCTK results
  README.md
Labels: enhancement

#103 Add parallel_wavegan.v3 config and results
  README.md
  egs/ljspeech/voc1/conf/parallel_wavegan.v3.yaml
Labels: enhancement

#104 Update README
  README.md
Labels: documentation

#107 Minor update
  egs/arctic/voc1/local/data_prep.sh
  egs/csmsc/voc1/local/data_prep.sh
  egs/csmsc/voc1/path.sh
  egs/jnas/voc1/local/data_prep.sh
  egs/jsut/voc1/local/data_prep.sh
  egs/ljspeech/voc1/local/data_prep.sh
  egs/vctk/voc1/local/data_prep.sh
  egs/yesno/voc1/local/data_prep.sh
Labels: enhancement

#108 Fix utt_id in the case of npy format
  parallel_wavegan/datasets/audio_mel_dataset.py
Labels: bug

#109 Add VCTK parallel_wavegan.v1.long result
  README.md
Labels: enhancement

#110 Add LibriTTS recipe
  egs/libritts/voc1/cmd.sh
  egs/libritts/voc1/conf/parallel_wavegan.v1.long.yaml
  egs/libritts/voc1/conf/parallel_wavegan.v1.yaml
  egs/libritts/voc1/conf/slurm.conf
  egs/libritts/voc1/local/data_download.sh
  egs/libritts/voc1/local/data_prep.sh
  egs/libritts/voc1/path.sh
  egs/libritts/voc1/run.sh
  parallel_wavegan/bin/decode.py
Labels: enhancement

#111 Support segments in libritts recipe
  egs/libritts/voc1/conf/parallel_wavegan.v1.long.yaml
  egs/libritts/voc1/conf/parallel_wavegan.v1.yaml
  egs/libritts/voc1/local/data_download.sh
  egs/libritts/voc1/local/data_prep.sh
  egs/libritts/voc1/run.sh
  egs/vctk/voc1/local/data_prep.sh
Labels: enhancement

#112 Support tensorflow melgan version for speedup inference time
  .gitignore
  notebooks/convert_melgan_from_pytorch_to_tensorflow.ipynb
  parallel_wavegan/layers/tf_layers.py
  parallel_wavegan/models/tf_models.py
Labels: enhancement

#114 Update README
  README.md
Labels: documentation

#115 Update tensorflow module & conversion notebook
  notebooks/convert_melgan_from_pytorch_to_tensorflow.ipynb
  parallel_wavegan/layers/tf_layers.py
  parallel_wavegan/models/tf_models.py
Labels: enhancement

#120 Support google colab in conversion notebook
  notebooks/convert_melgan_from_pytorch_to_tensorflow.ipynb
Labels: enhancement

#124 Add LibriTTS results
  README.md
Labels: enhancement

#127 Fix tensorflow version in colab notebook
  notebooks/convert_melgan_from_pytorch_to_tensorflow.ipynb
Labels: bug
