Repository kan-bayashi/ParallelWaveGAN, pull requests merged in 2020-01, with the labels that each got.

#45 add residual adversary to remove low freq checkerboard artifacts caus…
  egs/ljspeech/voc1/conf/parallel_wavegan.v1.yaml
  parallel_wavegan/bin/train.py
  parallel_wavegan/models/parallel_wavegan.py
Labels: enhancement

#47 Merge pull request #47 from kan-bayashi/feature/new_dicsriminator
  .github/workflows/ci.yaml
  egs/ljspeech/voc1/conf/parallel_wavegan.v1.yaml
  egs/ljspeech/voc1/conf/parallel_wavegan.v2.yaml
  parallel_wavegan/__init__.py
  parallel_wavegan/bin/train.py
  parallel_wavegan/layers/residual_block.py
  parallel_wavegan/models/parallel_wavegan.py
  setup.py
  test/test_parallel_wavegan.py
Labels: refactoring

#48 Add missing config
  README.md
  egs/ljspeech/voc1/conf/parallel_wavegan.v1.no_limit.yaml
Labels: enhancement

#49 Minor fix
  parallel_wavegan/__init__.py
  parallel_wavegan/bin/decode.py
  setup.py
Labels: refactoring

#50 Merge pull request #50 from kan-bayashi/minor_fix_2
  egs/arctic/voc1/local/data_download.sh
  egs/arctic/voc1/local/data_prep.sh
  egs/csmsc/voc1/local/data_download.sh
  egs/csmsc/voc1/local/data_prep.sh
  egs/jsut/voc1/local/data_download.sh
  egs/jsut/voc1/local/data_prep.sh
Labels: refactoring

#55 Add comment in run.sh
  README.md
  egs/arctic/voc1/run.sh
  egs/csmsc/voc1/run.sh
  egs/jsut/voc1/run.sh
  egs/ljspeech/voc1/run.sh
Labels: documentation

#56 Update github action
  .github/workflows/ci.yaml
Labels: enhancement

#57 Add JNAS recipe
  egs/jnas/voc1/cmd.sh
  egs/jnas/voc1/conf/parallel_wavegan.v1.yaml
  egs/jnas/voc1/conf/slurm.conf
  egs/jnas/voc1/conf/train_speakers.txt
  egs/jnas/voc1/local/data_prep.sh
  egs/jnas/voc1/path.sh
  egs/jnas/voc1/run.sh
Labels: enhancement

#58 Add initial JNAS results
  README.md
  egs/jnas/voc1/conf/parallel_wavegan.v1.long.yaml
Labels: enhancement

#60 Update data prep scripts
  egs/arctic/voc1/local/data_prep.sh
  egs/csmsc/voc1/local/data_prep.sh
  egs/jnas/voc1/local/data_prep.sh
  egs/jsut/voc1/local/data_prep.sh
  egs/ljspeech/voc1/local/data_prep.sh
  utils/split_data.sh
Labels: enhancement
