Repository kan-bayashi/ParallelWaveGAN, pull requests merged in 2021-08, with the labels that each got.

#272 Refactoring with black
  .github/workflows/ci.yaml
  README.md
  parallel_wavegan/bin/compute_statistics.py
  parallel_wavegan/bin/decode.py
  parallel_wavegan/bin/normalize.py
  parallel_wavegan/bin/preprocess.py
  parallel_wavegan/bin/train.py
  parallel_wavegan/datasets/audio_mel_dataset.py
  parallel_wavegan/datasets/scp_dataset.py
  parallel_wavegan/distributed/launch.py
  parallel_wavegan/layers/causal_conv.py
  parallel_wavegan/layers/pqmf.py
  parallel_wavegan/layers/residual_block.py
  parallel_wavegan/layers/residual_stack.py
  parallel_wavegan/layers/tf_layers.py
  parallel_wavegan/layers/upsample.py
  parallel_wavegan/models/melgan.py
  parallel_wavegan/models/parallel_wavegan.py
  parallel_wavegan/models/tf_models.py
  parallel_wavegan/optimizers/radam.py
  parallel_wavegan/utils/utils.py
  pyrightconfig.json
  setup.cfg
  setup.py
  test/test_layers.py
  test/test_melgan.py
  test/test_parallel_wavegan.py
Labels: refactoring

#273 Support HiFi-GAN
  .github/workflows/ci.yaml
  egs/ljspeech/voc1/conf/hifigan.v1.yaml
  egs/yesno/voc1/conf/hifigan.v1.debug.yaml
  parallel_wavegan/__init__.py
  parallel_wavegan/bin/train.py
  parallel_wavegan/layers/residual_block.py
  parallel_wavegan/losses/__init__.py
  parallel_wavegan/losses/adversarial_loss.py
  parallel_wavegan/losses/feat_match_loss.py
  parallel_wavegan/losses/stft_loss.py
  parallel_wavegan/models/__init__.py
  parallel_wavegan/models/hifigan.py
  parallel_wavegan/models/melgan.py
  parallel_wavegan/models/parallel_wavegan.py
  setup.py
  test/test_hifigan.py
  test/test_melgan.py
  test/test_parallel_wavegan.py
Labels: enhancement

#275 Update HiFi-GAN
  .github/workflows/ci.yaml
  .gitignore
  egs/ljspeech/voc1/conf/hifigan.v1.yaml
  egs/yesno/voc1/conf/hifigan.v1.debug.yaml
  parallel_wavegan/bin/train.py
  parallel_wavegan/losses/__init__.py
  parallel_wavegan/losses/mel_loss.py
  parallel_wavegan/models/hifigan.py
  test/test_hifigan.py
  test/test_mel_loss.py
Labels: enhancement

#274 Support StyleMelGAN
  .github/workflows/ci.yaml
  egs/ljspeech/voc1/conf/style_melgan.v1.yaml
  egs/yesno/voc1/conf/style_melgan.v1.debug.yaml
  parallel_wavegan/layers/__init__.py
  parallel_wavegan/layers/tade_res_block.py
  parallel_wavegan/models/__init__.py
  parallel_wavegan/models/style_melgan.py
  test/test_style_melgan.py
Labels: enhancement

#268 Added Speech Commands Dataset support
  egs/speech_commands/voc1/cmd.sh
  egs/speech_commands/voc1/conf/parallel_wavegan.v1.yaml
  egs/speech_commands/voc1/local/data_download.sh
  egs/speech_commands/voc1/local/data_prep.sh
  egs/speech_commands/voc1/path.sh
  egs/speech_commands/voc1/run.sh
  egs/speech_commands/voc1/utils
Labels: enhancement

#276 Fix residual calculation in HiFiGAN generator
  parallel_wavegan/layers/residual_block.py
Labels: bug

#277 Refactor HiFi-GAN
  egs/ljspeech/voc1/conf/hifigan.v1.yaml
  egs/yesno/voc1/conf/hifigan.v1.debug.yaml
  parallel_wavegan/bin/train.py
  parallel_wavegan/layers/residual_block.py
  parallel_wavegan/losses/adversarial_loss.py
  parallel_wavegan/losses/mel_loss.py
  parallel_wavegan/models/hifigan.py
Labels: refactoring

#281 Support hinge loss in adversarial loss
  parallel_wavegan/losses/adversarial_loss.py
  test/test_style_melgan.py
Labels: enhancement

#283 Prevent pop noise at the end of audio in StyleMelGAN inference
  parallel_wavegan/models/style_melgan.py
Labels: enhancement

#285 Add useful functions
  README.md
  egs/yesno/voc1/conf/parallel_wavegan.v1.debug.npy.yaml
  egs/yesno/voc1/run.sh
  parallel_wavegan/__init__.py
  parallel_wavegan/bin/decode.py
  parallel_wavegan/bin/preprocess.py
  parallel_wavegan/models/hifigan.py
  parallel_wavegan/models/melgan.py
  parallel_wavegan/models/parallel_wavegan.py
  parallel_wavegan/models/style_melgan.py
  parallel_wavegan/utils/utils.py
  setup.py
Labels: enhancement

#286 Minor update
  .github/workflows/ci.yaml
  parallel_wavegan/bin/compute_statistics.py
  setup.py
  tools/Makefile
Labels: enhancement

#288 Add configs for JSUT and LibriTTS
  egs/csmsc/voc1/conf/hifigan.v1.yaml
  egs/csmsc/voc1/conf/style_melgan.v1.yaml
  egs/jsut/voc1/conf/hifigan.v1.yaml
  egs/jsut/voc1/conf/style_melgan.v1.yaml
  egs/libritts/voc1/conf/hifigan.v1.yaml
  egs/libritts/voc1/conf/style_melgan.v1.yaml
  egs/vctk/voc1/conf/hifigan.v1.yaml
  egs/vctk/voc1/conf/style_melgan.v1.yaml
Labels: enhancement
